gocd-agent:
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    gocd.role: agent
  tty: true
  image: rawmind/rancher-goagent:16.2.1
  volumes:
    - ${volume_work}:/opt/go-agent/pipelines
  external_links:
    - ${goserver_ip}:gocd-server.rancher.internal
  environment:
    - AGENT_MEM=${mem_initial}m
    - AGENT_MAX_MEM=${mem_max}m
    - HOST_PIPELINES_VOL=${volume_work}
    - GO_SERVER=gocd-server.rancher.internal
    - GO_SERVER_PORT=${goserver_port}
